### ISSUE TITLE
npm start is wrong

### ISSUE THREAD

**Issue by Mukangsong** [VegeBun-csj/MedRec#1]
![image](https://user-images.githubusercontent.com/59683194/92066699-2141d180-edd5-11ea-96ac-25d71cebefe1.png)

**Comment by VegeBun-csj** [comment]
ok guys , this is a bug my "npm package file" when i first use node,js to build the project. you can rebuild the package.json and `npm install ` 
 I will improve the Deployment process of this project in the next few days.

**Comment by Mukangsong** [comment]
能把运行过程写的详细点吗？？谢谢！

**Comment by VegeBun-csj** [comment]
ok

**Comment by Mukangsong** [comment]
是不是针对package.json进行修改，就可以运行了？？？

**Comment by VegeBun-csj** [comment]
不是，还有其他的一些改动，这是我上传的老版本，近期我会上传（最近有点忙）

**Comment by Mukangsong** [comment]
这是一个前后端都具备的完整系统？？？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "VegeBun"<notifications@github.com&gt;; 
发送时间: 2020年9月14日(星期一) 中午1:40
收件人: "VegeBun-csj/MedRec"<MedRec@noreply.github.com&gt;; 
抄送: "2232644011"<2232644011@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [VegeBun-csj/MedRec] npm start is wrong (#1)





 
不是，还有其他的一些改动，这是我上传的老版本，近期我会上传（最近有点忙）

**Comment by VegeBun-csj** [comment]
是的

**Comment by Mukangsong** [comment]
已经可以，谢谢您。



---Original---
