### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Mukangsong** [VegeBun-csj/MedRec#2]
您数据库密码多少？我连不上是不是因为数据库密码不对？

**Comment by Mukangsong** [comment]
mu@mu-virtual-machine:~/go/src/github.com/hyperledger/MedRec/App/server/patient$ node app
Server has started at 8081 port !!!
Connection error: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

**Comment by Mukangsong** [comment]
密码找到了，是password，改过node.js还连接拒绝是什么原因？？？

**Comment by VegeBun-csj** [comment]
更新一下App/server/config.json文件中的dbpassword和database字段，部署文档已经更新

**Comment by VegeBun-csj** [comment]
启动后端之前请修改server目录中的config.json文件中的database和dbpassword字段为自己的数据库和密码（我这里新建的数据库名是MedRec，密码是csj123zxc，所以只需要修改为你自己的数据库名和密码即可），部署文档中已经更新

**Comment by Mukangsong** [comment]
已经改过了，成功了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: VegeBun <notifications@github.com&gt;
发送时间: 2020年9月17日 13:20
收件人: VegeBun-csj/MedRec <MedRec@noreply.github.com&gt;
抄送: Mukangsong <2232644011@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[VegeBun-csj/MedRec] 问题 (#2)





 
启动后端之前请修改server目录中的config.json文件中的database和dbpassword字段为自己的数据库和密码（我这里新建的数据库名是MedRec，密码是csj123zxc，所以只需要修改为你自己的数据库名和密码即可），部署文档中已经更新

**Comment by Mukangsong** [comment]
这个项目是fabric一定要1.4.4，出现这种错是版本的问题吗？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VegeBun-csj/MedRec"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月17日(星期四) 中午1:20
收件人:&nbsp;"VegeBun-csj/MedRec"<MedRec@noreply.github.com&gt;;
抄送:&nbsp;"2232644011"<2232644011@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VegeBun-csj/MedRec] 问题 (#2)





 
启动后端之前请修改server目录中的config.json文件中的database和dbpassword字段为自己的数据库和密码（我这里新建的数据库名是MedRec，密码是csj123zxc，所以只需要修改为你自己的数据库名和密码即可），部署文档中已经更新

**Comment by Mukangsong** [comment]
启动./start.sh up 保错
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg cannot get package for chaincode (recordpb:1.0)

**Comment by Mukangsong** [comment]
已经成功了，果然是版本的问题

**Comment by VegeBun-csj** [comment]
项目本身是1.4.4版本的，有可能是版本问题，但是不一定是版本问题，这种启动网络中中出现的错误，一般重启网络即可解决

**Comment by Mukangsong** [comment]
嗯，重新装了1.4.4的镜像，可以运行了，谢谢。



---原始邮件---
发件人: "VegeBun"<notifications@github.com&gt;
发送时间: 2020年9月20日(周日) 晚上9:37
收件人: "VegeBun-csj/MedRec"<MedRec@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Mukangsong"<2232644011@qq.com&gt;;
主题: Re: [VegeBun-csj/MedRec] 问题 (#2)




 
项目本身是1.4.4版本的，有可能是版本问题，但是不一定是版本问题，这种启动网络中中出现的错误，一般重启网络即可解决
